// <auto-generated />
using System;
using Code_First_PostgreSQL_Web_Api.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Code_First_PostgreSQL_Web_Api.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20190830174710_Initial_Library")]
    partial class Initial_Library
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Code_First_PostgreSQL_Web_Api.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("AuthorId");

                    b.HasIndex("FirstName");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Code_First_PostgreSQL_Web_Api.Models.AuthorBiography", b =>
                {
                    b.Property<int>("AuthorBiographyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<string>("Biography");

                    b.Property<DateTimeOffset>("DateOfBirth");

                    b.Property<string>("Nationality");

                    b.Property<string>("PlaceOfBirth");

                    b.HasKey("AuthorBiographyId");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.HasIndex("Nationality");

                    b.ToTable("AuthorBiographies");
                });

            modelBuilder.Entity("Code_First_PostgreSQL_Web_Api.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<string>("Title");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Code_First_PostgreSQL_Web_Api.Models.AuthorBiography", b =>
                {
                    b.HasOne("Code_First_PostgreSQL_Web_Api.Models.Author", "Author")
                        .WithOne("Biography")
                        .HasForeignKey("Code_First_PostgreSQL_Web_Api.Models.AuthorBiography", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Code_First_PostgreSQL_Web_Api.Models.Book", b =>
                {
                    b.HasOne("Code_First_PostgreSQL_Web_Api.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
